In [ ]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Preprocessing Data and merging stringency index and health expenditure

In [ ]:
clean_cd_df = pd.read_csv("/content/drive/MyDrive/DA_Project_files/All_datasets/Covidistress_final.csv")
health_expend_df = pd.read_csv("/content/drive/MyDrive/DA_Project_files/All_datasets/Healthcare_expenditure.csv")
string_ind_df = pd.read_csv("/content/drive/MyDrive/DA_Project_files/All_datasets/covid-stringency-index.csv")


In [ ]:
clean_cd_df['avg_stress'] = (clean_cd_df['Scale_PSS10_UCLA_1']+ clean_cd_df['Scale_PSS10_UCLA_1']+clean_cd_df['Scale_PSS10_UCLA_2']+clean_cd_df['Scale_PSS10_UCLA_3']+clean_cd_df['Scale_PSS10_UCLA_4']+clean_cd_df['Scale_PSS10_UCLA_5']+clean_cd_df['Scale_PSS10_UCLA_6']+clean_cd_df['Scale_PSS10_UCLA_7']+clean_cd_df['Scale_PSS10_UCLA_8']+clean_cd_df['Scale_PSS10_UCLA_9']+clean_cd_df['Scale_PSS10_UCLA_10'])/10

In [ ]:
clean_cd_df = clean_cd_df.loc[clean_cd_df['avg_stress'] != 0]

In [ ]:
health_expend_df = health_expend_df.drop(health_expend_df.index[0])

In [ ]:
health_expend_df = health_expend_df.drop(labels = ['Unnamed: 1','Unnamed: 2', 'Unnamed: 3'] , axis = 1)

In [ ]:
health_expend_df.fillna(0)

Year  2010  2011  2012  ...  2017  2018  2019  2020
1                      Australia  68.6  69.2  67.5  ...  66.3  66.6  68.7    ..
2                        Austria  74.6  74.6  74.7  ...  74.0  74.8  75.2  76.4
3                        Belgium  76.1  76.1  76.6  ...  77.4  76.9  76.8    ..
4                         Canada  69.9  70.2  70.4  ...  69.8  70.2  70.2    ..
5                          Chile  59.0  59.5  60.0  ...  60.1  60.3  60.6  62.8
6                       Colombia  74.8  76.0  73.9  ...  76.6  77.3  77.5    ..
7                     Costa Rica  73.1  73.0  74.1  ...  75.0  73.8  73.9    ..
8                 Czech Republic  83.3  83.9  83.7  ...  82.1  83.0  81.8    ..
9                        Denmark  83.9  83.6  84.0  ...  84.0  83.9  83.3    ..
10                       Estonia  76.3  76.7  76.7  ...  73.6  73.7  74.5  78.2
11                       Finland  77.1  77.6  78.2  ...  76.4  76.9  77.8    ..
12                        France  76.3  76.0  76.1  ...  83.2  83.5  83.7    ..
13                       Germany  83.2  83.1  83.0  ...  84.5  84.5  84.6  85.1
14                        Greece  68.9  65.7  66.1  ...  60.5  58.4  59.8    ..
15                       Hungary  67.1  66.5  65.5  ...  68.8  69.9  68.3    ..
16                       Iceland  79.9  80.0  79.9  ...  82.0  82.5  82.9  83.8
17                       Ireland  76.2  71.9  71.7  ...  73.0  74.1  74.6  77.1
18                        Israel  62.8  62.6  62.6  ...  63.9  64.6  64.8    ..
19                         Italy  78.5  77.0  75.9  ...  73.7  73.8  73.9  76.3
20                         Japan  81.9  83.7  83.9  ...  84.2  83.8  83.9    ..
21                         Korea  60.9  60.0  59.1  ...  59.6  60.1    61  62.2
22                     Lithuania  71.7  71.0  67.3  ...  66.1  67.2  66.4  66.4
23                        Latvia  60.2  63.5  60.3  ...  57.3  59.9  61.5    ..
24                    Luxembourg  84.9  83.2  82.8  ...  84.0  84.1    85    ..
25                        Mexico  50.2  52.8  53.1  ...  50.5  49.7  49.3    ..
26                   Netherlands  83.4  82.7  82.1  ...  81.7  82.1  82.6  84.6
27                   New Zealand  81.2  80.9  80.5  ...  78.6  79.2  79.7    ..
28                        Norway  84.7  84.4  84.8  ...  85.1  85.7  85.8    86
29                        Poland  71.7  70.9  70.0  ...  69.3  71.5  71.8  73.3
30                      Portugal  66.6  64.6  61.3  ...  61.2  61.2    61  65.1
31               Slovak Republic  71.9  73.8  72.2  ...  79.9  80.1  79.8    ..
32                      Slovenia  73.4  73.4  72.0  ...  72.2  72.8  72.8  76.2
33                         Spain  74.4  73.5  72.1  ...  70.5  70.3  70.6    ..
34                        Sweden  82.5  84.5  84.2  ...  84.7  84.8  84.9  85.1
35                   Switzerland  64.3  64.8  66.2  ...  65.9  65.7  66.8    ..
36                        Turkey  78.0  79.1  79.2  ...  77.7  77.4  77.9    ..
37                United Kingdom  81.7  81.4  80.7  ...  78.9  78.5  78.5  81.7
38                 United States  48.7  48.8  48.7  ...  82.6  82.8  82.7    ..
39  China (People's Republic of)  51.9  53.7  55.7  ...  56.7  56.6    ..    ..
40                         India  25.5  28.0  27.1  ...  27.5  27.2    ..    ..
41                     Indonesia  26.3  27.6  30.5  ...  47.2  49.9    ..    ..
42                        Russia  61.4  62.7  63.7  ...  57.1  59.5  61.2    ..
43                  South Africa  40.9  42.5  43.3  ...  42.8  43.1    ..    ..

[43 rows x 12 columns]

In [ ]:
health_expend_df = health_expend_df.replace('..', int(0))

In [ ]:
health_expend_df  = health_expend_df.astype({'2019':'float64'})

In [ ]:
health_expend_new_df = pd.DataFrame()
health_expend_new_df['Country'] = health_expend_df['Year']

health_expend_new_df['Avg_10-19'] = health_expend_df.mean(axis = 1)

In [ ]:
combined_new_df = pd.DataFrame()
combined_new_df = pd.merge(left = clean_cd_df, right = health_expend_new_df, how = 'left', left_on = 'Country', right_on = 'Country')

In [ ]:
string_ind_df["Day"]=pd.to_datetime(string_ind_df["Day"])

In [ ]:
string_ind_df=string_ind_df[(pd.DatetimeIndex(string_ind_df["Day"]).year==2020)&(pd.DatetimeIndex(string_ind_df["Day"]).month<6)]

In [ ]:
string_ind_df = string_ind_df.groupby("Entity")["stringency_index"].mean()

In [ ]:
combined_new_df = pd.merge(left = combined_new_df, right = string_ind_df, how = 'left', left_on= 'Country', right_on = 'Entity')

In [ ]:
combined_new_df = combined_new_df.drop('Dem_state', axis = 1)

In [ ]:
combined_new_df = combined_new_df.drop(labels = ['Scale_PSS10_UCLA_1', 'Scale_PSS10_UCLA_2', 'Scale_PSS10_UCLA_3',
       'Scale_PSS10_UCLA_4', 'Scale_PSS10_UCLA_5', 'Scale_PSS10_UCLA_6',
       'Scale_PSS10_UCLA_7', 'Scale_PSS10_UCLA_8', 'Scale_PSS10_UCLA_9',
       'Scale_PSS10_UCLA_10',], axis = 1)

In [ ]:
new_list = ['Expl_Coping_1', 'Expl_Coping_2', 'Expl_Coping_3', 'Expl_Coping_4',
       'Expl_Coping_5', 'Expl_Coping_6', 'Expl_Coping_7', 'Expl_Coping_8',
       'Expl_Coping_9', 'Expl_Coping_10', 'Expl_Coping_11', 'Expl_Coping_12',
       'Expl_Coping_13', 'Expl_Coping_14', 'Expl_Coping_15', 'Expl_Coping_16']

combined_new_df['Avg_Coping'] = combined_new_df['Expl_Coping_1']
for i in new_list:
  combined_new_df['Avg_Coping'] += combined_new_df[i]/16

In [ ]:
combined_new_df = combined_new_df.drop(labels = ['Expl_Coping_1', 'Expl_Coping_2', 'Expl_Coping_3', 'Expl_Coping_4',
       'Expl_Coping_5', 'Expl_Coping_6', 'Expl_Coping_7', 'Expl_Coping_8',
       'Expl_Coping_9', 'Expl_Coping_10', 'Expl_Coping_11', 'Expl_Coping_12',
       'Expl_Coping_13', 'Expl_Coping_14', 'Expl_Coping_15', 'Expl_Coping_16'], axis = 1)

# Label Encoding Categorical variable

In [ ]:
combined_new_df_cat =combined_new_df.select_dtypes(['object']).apply(pd.Series.astype,dtype='category')

In [ ]:
cols=combined_new_df_cat.select_dtypes(['category']).columns.to_list()

In [ ]:
combined_new_df_nona = combined_new_df_cat.dropna(how = "any")

In [ ]:
for k in combined_new_df_nona.columns:
 print(k, combined_new_df_nona[k].isnull().values.any())

Dem_gender False
Dem_edu False
Dem_edu_mom False
Dem_employment False
Country False
Dem_Expat False
Dem_maritalstatus False
Dem_riskgroup False
Dem_isolation False


In [ ]:
from sklearn.preprocessing import LabelEncoder
label_object = {}
for col in cols:
    labelencoder = LabelEncoder()
    labelencoder.fit(combined_new_df_nona[col])
    combined_new_df_nona[col] = labelencoder.fit_transform(combined_new_df_nona[col])
    label_object[col] = labelencoder



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
for i in combined_new_df_nona.columns:
  combined_new_df[i] = combined_new_df_nona[i]

In [ ]:
combined_final = combined_new_df.drop(labels = ['Unnamed: 0', 'Dem_isolation_adults', 'Dem_isolation_kids', 'AD_gain', 'AD_loss'] , axis = 1)

In [ ]:
combined_final_small = combined_final.dropna(how = "any")

In [ ]:
X_values = combined_final_small.columns.to_list()

In [ ]:
(X_values).remove('avg_stress')

In [ ]:
(X_values).remove('PSS10_avg')

# AdaBoost 

In [ ]:
bins = [0, 1, 2, 3, 4, 5, 6]
labels = [1,2,3,4,5,6]

In [ ]:
combined_final_small['avg_stress'] = pd.cut(combined_final_small['avg_stress'], bins = bins, labels =labels)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


In [ ]:
X = combined_final_small[X_values]
y = combined_final_small['avg_stress']

In [ ]:
X

Dem_age  Dem_gender  Dem_edu  ...  Avg_10-19  stringency_index  Avg_Coping
4            68         1.0      0.0  ...      75.28         64.064394      9.1875
18           69         0.0      2.0  ...      51.50         42.804621      9.9375
19           28         0.0      2.0  ...      79.11         56.309167      7.5625
20           67         0.0      3.0  ...      51.50         42.804621      8.0625
28           33         0.0      0.0  ...      69.16         45.521061      4.7500
...         ...         ...      ...  ...        ...               ...         ...
116087       58         1.0      0.0  ...      83.95         44.100833      8.2500
116088       28         1.0      0.0  ...      83.95         44.100833      8.0000
116091       33         1.0      3.0  ...      83.95         44.100833      7.8125
116095       54         1.0      3.0  ...      83.95         44.100833      9.1250
116096       57         0.0      5.0  ...      83.95         44.100833      8.8125

[63552 rows x 43 columns]

In [ ]:
from sklearn.ensemble import AdaBoostClassifier


In [ ]:
clf2 = AdaBoostClassifier(n_estimators=100)

In [ ]:
clf2.fit(X,y)

AdaBoostClassifier(n_estimators=100)

Adaboost (estimators = 100) accuracy = 0.607140609264854

The accuracy is not changing if the number of estimators are changed. 

In [ ]:
y

4         3
18        3
19        4
20        4
28        4
         ..
116087    3
116088    3
116091    4
116095    4
116096    5
Name: avg_stress, Length: 63552, dtype: category
Categories (6, int64): [1 < 2 < 3 < 4 < 5 < 6]

In [ ]:
clf2.score(X,y)

0.607140609264854

In [ ]:
clf2.feature_importances_

array([0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.5,
       0.5, 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ,
       0. , 0. , 0. , 0. ])

In [ ]:
clf2.n_classes_

6

In [ ]:
clf2.base_estimator_

DecisionTreeClassifier(max_depth=1)

In [ ]:
clf2.estimators_

[DecisionTreeClassifier(max_depth=1, random_state=1527225429),
 DecisionTreeClassifier(max_depth=1, random_state=1566425714),
 DecisionTreeClassifier(max_depth=1, random_state=2131284226),
 DecisionTreeClassifier(max_depth=1, random_state=36800022),
 DecisionTreeClassifier(max_depth=1, random_state=774282736),
 DecisionTreeClassifier(max_depth=1, random_state=362375058),
 DecisionTreeClassifier(max_depth=1, random_state=1320268738),
 DecisionTreeClassifier(max_depth=1, random_state=1042269041),
 DecisionTreeClassifier(max_depth=1, random_state=687288615),
 DecisionTreeClassifier(max_depth=1, random_state=377777004),
 DecisionTreeClassifier(max_depth=1, random_state=1394526991),
 DecisionTreeClassifier(max_depth=1, random_state=2021755093),
 DecisionTreeClassifier(max_depth=1, random_state=1741081501),
 DecisionTreeClassifier(max_depth=1, random_state=1345700984),
 DecisionTreeClassifier(max_depth=1, random_state=1361993276),
 DecisionTreeClassifier(max_depth=1, random_state=757692661),

In [ ]:
clf2.estimator_weights_

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
clf2.estimator_errors_

array([0.39259189, 0.666906  , 0.66670989, 0.66674911, 0.66667367,
       0.66668106, 0.66666943, 0.66667212, 0.66666842, 0.66666984,
       0.6666681 , 0.66666901, 0.66666799, 0.66666865, 0.66666797,
       0.66666847, 0.66666799, 0.66666839, 0.66666803, 0.66666835,
       0.66666807, 0.66666833, 0.66666811, 0.66666832, 0.66666814,
       0.66666832, 0.66666818, 0.66666832, 0.66666821, 0.66666832,
       0.66666823, 0.66666832, 0.66666825, 0.66666833, 0.66666827,
       0.66666833, 0.66666828, 0.66666833, 0.66666829, 0.66666834,
       0.6666683 , 0.66666834, 0.66666831, 0.66666834, 0.66666832,
       0.66666834, 0.66666832, 0.66666834, 0.66666833, 0.66666834,
       0.66666833, 0.66666834, 0.66666834, 0.66666835, 0.66666834,
       0.66666835, 0.66666834, 0.66666835, 0.66666834, 0.66666835,
       0.66666834, 0.66666835, 0.66666834, 0.66666835, 0.66666834,
       0.66666835, 0.66666835, 0.66666835, 0.66666835, 0.66666835,
       0.66666835, 0.66666835, 0.66666835, 0.66666835, 0.66666

# AdaBoost using repeated stratified k-fold cross-validation, with three repeats and 10 folds. 

In [ ]:
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RepeatedStratifiedKFold
# evaluate adaboost algorithm for classification
from numpy import mean
from numpy import std

In [ ]:
clf3 = AdaBoostClassifier(n_estimators=100)

In [ ]:
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

In [ ]:
n_scores = cross_val_score(clf3, X, y, scoring='accuracy', cv=cv, n_jobs=-1, error_score='raise')


In [ ]:
n_scores

array([0.60462555, 0.61359346, 0.59653816, 0.60991345, 0.61195909,
       0.60047207, 0.60991345, 0.60692368, 0.60550747, 0.61195909,
       0.60478288, 0.60997483, 0.60708104, 0.60629426, 0.60959874,
       0.60346184, 0.60487805, 0.60818253, 0.60660897, 0.61054288,
       0.6003776 , 0.60179358, 0.60519276, 0.60409127, 0.60173092,
       0.61148702, 0.61636507, 0.6086546 , 0.6122738 , 0.60944138])

Mean accuracy = 0.607, std dev = 0.004

In [ ]:
print('Accuracy: %.3f (%.3f)' % (mean(n_scores), std(n_scores)))

Accuracy: 0.607 (0.004)


# Permutation_importance to obtain important features

In [ ]:
clf4 = AdaBoostClassifier(n_estimators=100)

In [ ]:
clf4.fit(X,y)

AdaBoostClassifier(n_estimators=100)

In [ ]:
from sklearn.inspection import permutation_importance

result = permutation_importance(clf4, X, y,random_state=0)

This implies that Scale_SLON_2 and Scale_SLON_3 are significant in classifying avg_stress. This re-iterates what we've seen with Decision trees. Every other feature seems to have a very low significance. 

In [ ]:
result.importances_mean

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.10358761, 0.00015735, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        ])

In [ ]:
result.importances_std

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       2.24364423e-03, 9.64860883e-05, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00])

# XGBOOST

XGBOOST

In [ ]:
import xgboost as xgb
from sklearn.metrics import mean_squared_error
import pandas as pd
import numpy as np

In [ ]:
y = y.replace({1: 0, 2: 1,3: 2, 4: 3,5: 4, 6: 5})

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

In [ ]:
xg_reg = xgb.XGBRegressor(objective ='multi:softmax', colsample_bytree = 0.3, learning_rate = 0.1,
                max_depth = 5, alpha = 10, n_estimators = 100, num_class = 6)

In [ ]:

xg_reg.fit(X_train,y_train)

preds = xg_reg.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, preds)

0.6713869876484935

In [ ]:
from sklearn.metrics import cohen_kappa_score
cohen_kappa_score(y_test, preds)

0.3233801493182632

In [ ]:
from sklearn.metrics import precision_score
precision_score(y_test, preds, average= 'micro')

0.6721737078121313